### ISSUE TITLE
onEvents(), onError() not working

### ISSUE THREAD

**Issue by Warface** [radarlabs/cordova-plugin-radar#1]
Every functions seems to work but the listeners aren't

I've set an interval to trackOnce every minutes and added the listener

cordova.plugins.radar.onEvents((events, user) => {
    console.log(events, user);
});

The console.log returns nothing while I'm faking the GPS outside and inside the geofence zone

And this is in Foreground, I hope this listener supposed to work both foreground and background.

**Comment by Warface** [comment]
I've found the problem! In the manifest, I don't know why, the <receiver> wasn't even there. I had to add it manually and fix the android:name path so it point to the good Class in Android Studio.

The event is firing now!

So make sure that in the manifest, these are writen in the <application> node

```
        <receiver
            android:name=".RadarCordovaPlugin$RadarCordovaReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="io.radar.sdk.RECEIVED" />
            </intent-filter>
        </receiver>
```

And make sure the path is ok for the Class in android:name

**Comment by nickpatrick** [comment]
Great! Feel free to open another issue if you have any other issues or feedback.

**Comment by Warface** [comment]
@nickpatrick I did and still no answer from your part
